// https://gist.github.com/EvanBacon/98858a341e2da209587455bbad465931
const includesEverything = {
  CFBundleDocumentTypes: [
    {
      CFBundleTypeExtensions: ["*"],
      CFBundleTypeName: "All files",
      CFBundleTypeOSTypes: ["*"],
    },
    {
      CFBundleTypeExtensions: ["mov"],
      CFBundleTypeName: "MovieDocument",
      CFBundleTypeOSTypes: ["MooV"],
      CFBundleTypeMIMETypes: ["movie/quicktime"],
      CFBundleTypeRole: "Editor",
      NSDocumentClass: "MovieDocument",
    },
    {
      CFBundleTypeExtensions: ["mp4", "m4v"],
      CFBundleTypeMIMETypes: ["video/mp4", "application/mp4", "audio/mp4"],
      CFBundleTypeName: "MP4 Video",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeName: "Folder",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.folder"],
    },
    {
      CFBundleTypeName: "Volume",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.volume"],
    },
    {
      CFBundleTypeIconFile: "flv.icns",
      CFBundleTypeName: "Flash Video File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["com.adobe.flash.video"],
    },
    {
      CFBundleTypeExtensions: ["gvp"],
      CFBundleTypeIconFile: "playlist.icns",
      CFBundleTypeName: "Google Video Playlist",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["dvdmedia"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "DVD Media Document",
      CFBundleTypeRole: "Editor",
      LSTypeIsPackage: true,
    },
    {
      CFBundleTypeExtensions: ["xspf"],
      CFBundleTypeIconFile: "playlist.icns",
      CFBundleTypeMIMETypes: ["application/xspf+xml"],
      CFBundleTypeName: "XSPF Playlist",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["xa"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "The Sims Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["xesc"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "Expression Encoder Screen Capture File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "playlist.icns",
      CFBundleTypeName: "Shoutcast playlist",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.pls-playlist"],
    },
    {
      CFBundleTypeIconFile: "playlist.icns",
      CFBundleTypeName: "Playlist file",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.m3u-playlist"],
    },
    {
      LSItemContentTypes: ["org.videolan.vlc"],
      CFBundleTypeIconFile: "playlist.icns",
      CFBundleTypeName: "VLC file",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "playlist.icns",
      CFBundleTypeName: "ASX file",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["com.microsoft.advanced-stream-redirector"],
    },
    {
      CFBundleTypeExtensions: ["b4s"],
      CFBundleTypeIconFile: "playlist.icns",
      CFBundleTypeName: "B4S file",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["ape"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "Monkey's Audio Lossless Audio Compression",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "FLAC Audio File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["org.xiph.flac"],
    },
    {
      CFBundleTypeExtensions: ["wv"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "WavePack Audio File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["tta"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "True Audio Free Lossless Audio",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["mpc"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "Musepack Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "rm.icns",
      CFBundleTypeName: "RealPlayer Media Files",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: [
        "com.real.realmedia-vbr",
        "com.real.realaudio",
        "com.real.realmedia",
      ],
    },
    {
      CFBundleTypeExtensions: ["img"],
      CFBundleTypeIconFile: "generic.icns",
      CFBundleTypeName: "IMG Disk Image",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["mod", "xm"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "MOD Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["it"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "Impulse Tracker Module File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["xm"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "XM audio file",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeIconFile: "aiff.icns",
      CFBundleTypeName: "AIFF file",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.aiff-audio", "public.aifc-audio"],
    },
    {
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "Adaptive Multi-Rate Codec File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["org.3gpp.adaptive-multi-rate-audio"],
    },
    {
      CFBundleTypeExtensions: ["aob"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "DVD-Audio Audio Object File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["dts"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "DTS Encoded Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["spx"],
      CFBundleTypeIconFile: "ogg.icns",
      CFBundleTypeMIMETypes: ["audio/ogg"],
      CFBundleTypeName: "Speex Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["sdp"],
      CFBundleTypeIconFile: "generic.icns",
      CFBundleTypeName: "Session Description Protocol File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "wav.icns",
      CFBundleTypeName: "WAVE Audio File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["com.microsoft.waveform-audio"],
    },
    {
      CFBundleTypeExtensions: ["vob"],
      CFBundleTypeIconFile: "vob.icns",
      CFBundleTypeName: "VOB File (DVD Video)",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["dat"],
      CFBundleTypeIconFile: "generic.icns",
      CFBundleTypeName: "DAT file",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["cue"],
      CFBundleTypeIconFile: "generic.icns",
      CFBundleTypeName: "CUE file",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["cdg"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "Compact Disc Plus Graphics Image file",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "generic.icns",
      CFBundleTypeName: "ISO file",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.iso-image"],
    },
    {
      CFBundleTypeExtensions: ["idx"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "Index file",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "Digital Audio",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.ac3-audio"],
    },
    {
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "AAC file",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.aac-audio"],
    },
    {
      CFBundleTypeExtensions: ["opus"],
      CFBundleTypeIconFile: "ogg.icns",
      CFBundleTypeMIMETypes: ["audio/opus", "audio/ogg; codecs=opus"],
      CFBundleTypeName: "OPUS file",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["org.xiph.opus"],
    },
    {
      CFBundleTypeExtensions: ["ogm"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "Ogg MPEG-4 Video File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["ogg"],
      CFBundleTypeIconFile: "ogg.icns",
      CFBundleTypeMIMETypes: ["audio/ogg"],
      CFBundleTypeName: "Ogg Vorbis File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["oga"],
      CFBundleTypeIconFile: "ogg.icns",
      CFBundleTypeMIMETypes: ["audio/ogg"],
      CFBundleTypeName: "Ogg Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["ogv"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeMIMETypes: ["video/ogg"],
      CFBundleTypeName: "Ogg Video File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["org.xiph.ogg-video"],
    },
    {
      CFBundleTypeExtensions: ["ogx"],
      CFBundleTypeIconFile: "ogg.icns",
      CFBundleTypeMIMETypes: ["application/ogg"],
      CFBundleTypeName: "Ogg Application File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["oma"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "Sony OpenMG Music File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["voc"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "Creative Labs Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["vqf"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "TwinVQ Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["anx"],
      CFBundleTypeIconFile: "generic.icns",
      CFBundleTypeMIMETypes: ["application/annodex"],
      CFBundleTypeName: "Annodex Application File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["axa"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeMIMETypes: ["audio/annodex"],
      CFBundleTypeName: "Annodex Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["axv"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeMIMETypes: ["video/annodex"],
      CFBundleTypeName: "Annodex Video File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["gxf"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "General eXchange Format File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["mxf"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "Material Exchange Format",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeIconFile: "avi.icns",
      CFBundleTypeName: "AVI container",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.avi"],
    },
    {
      CFBundleTypeExtensions: ["bik"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "Bink Video File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["crf"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "CRF Video File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["evo"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "EVO Video File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "mov.icns",
      CFBundleTypeName: "Apple QuickTime container",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["com.apple.quicktime-movie"],
    },
    {
      CFBundleTypeExtensions: ["divx"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "DivX file",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "DV file",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.dv-movie"],
    },
    {
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "Advanced Streaming Format",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["com.microsoft.advanced-systems-format"],
    },
    {
      CFBundleTypeIconFile: "wma.icns",
      CFBundleTypeName: "Windows Media Audio",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["com.microsoft.windows-media-wma"],
    },
    {
      CFBundleTypeIconFile: "wmv.icns",
      CFBundleTypeName: "Windows Media Video",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: [
        "com.microsoft.windows-media-wm",
        "com.microsoft.windows-media-wmv",
      ],
    },
    {
      CFBundleTypeExtensions: ["wtv"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "Windows Recorded TV Show",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "mpeg.icns",
      CFBundleTypeName: "multiplexed MPEG-1/2",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.mpeg"],
    },
    {
      CFBundleTypeExtensions: ["m1v"],
      CFBundleTypeIconFile: "mpeg.icns",
      CFBundleTypeName: "MPEG-1 Video File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["m2a"],
      CFBundleTypeIconFile: "mpeg.icns",
      CFBundleTypeName: "MPEG-1/2 Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["mp1"],
      CFBundleTypeIconFile: "mpeg.icns",
      CFBundleTypeName: "MPEG Audio Layer 1",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "mpeg.icns",
      CFBundleTypeName: "MPEG Audio Layer 2",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.mp2"],
    },
    {
      CFBundleTypeIconFile: "mp3.icns",
      CFBundleTypeName: "MPEG Audio Layer 3",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.mp3"],
    },
    {
      CFBundleTypeExtensions: ["m2p", "ps"],
      CFBundleTypeIconFile: "mpeg.icns",
      CFBundleTypeName: "MPEG-2 Program Stream",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["tp", "ts", "m2ts", "mts", "mt2s"],
      CFBundleTypeIconFile: "mpeg.icns",
      CFBundleTypeMIMETypes: ["video/mp2t"],
      CFBundleTypeName: "MPEG-2 Transport Stream",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "mpeg.icns",
      CFBundleTypeName: "MPEG-2 Video File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.mpeg-2-video"],
    },
    {
      CFBundleTypeExtensions: ["mpa"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "MPEG-2 Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "m4v.icns",
      CFBundleTypeName: "MPEG-4 File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: [
        "public.mpeg-4-audio",
        "com.apple.m4v-video",
        "public.mpeg-4",
      ],
    },
    {
      CFBundleTypeIconFile: "m4a.icns",
      CFBundleTypeName: "MPEG-4 Audio File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["com.apple.m4a-audio"],
    },
    {
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "3GPP File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.3gpp"],
    },
    {
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "MIDI File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["public.midi-audio"],
    },
    {
      CFBundleTypeExtensions: ["mlp"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "Meridian Lossless Packing Audio File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "Matroska Audio File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["org.matroska.mka"],
    },
    {
      CFBundleTypeExtensions: ["mkv"],
      CFBundleTypeIconFile: "mkv.icns",
      CFBundleTypeName: "Matroska Video File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["webm"],
      CFBundleTypeIconFile: "mkv.icns",
      CFBundleTypeName: "WebM Video File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["rar"],
      CFBundleTypeIconFile: "generic.icns",
      CFBundleTypeName: "WinRAR Compressed Archive",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["com.rarlab.rar-archive"],
    },
    {
      CFBundleTypeExtensions: ["rec"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "Topfield PVR Recording",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["rmi"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "RMID MIDI File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["s3m"],
      CFBundleTypeIconFile: "audio.icns",
      CFBundleTypeName: "ScreamTracker 3 Module",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["vro"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "DVD Video Recording Format",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["tod"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "JVC Everio Video Capture File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["mks"],
      CFBundleTypeIconFile: "mkv.icns",
      CFBundleTypeName: "Matroska Elementry Stream",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["nsv"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeMIMETypes: ["video/nsv"],
      CFBundleTypeName: "Nullsoft Streaming Video",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["nuv"],
      CFBundleTypeIconFile: "movie.icns",
      CFBundleTypeName: "NuppleVideo File",
      CFBundleTypeRole: "Viewer",
      LSItemContentTypes: ["com.mythtv.nuv"],
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["ssa", "ass"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "Sub Station Alpha Subtitle File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["usf"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "USF Subtitle File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "XML",
    },
    {
      CFBundleTypeExtensions: ["utf"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "UTF Subtitle File",
      CFBundleTypeRole: "Viewer",
    },
    {
      CFBundleTypeExtensions: ["srt"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "Subrip Subtitle File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["rt"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "RealText Subtitle File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["smi"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "SAMI Subtitle File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["aqt"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "AQTitle Subtitle File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["jss"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "JACOSub Subtitle File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["pjs"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "Phoenix Subtitle File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["psb"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "PowerDivX Subtitle File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
    {
      CFBundleTypeExtensions: ["sub", "mpsub"],
      CFBundleTypeIconFile: "subtitle.icns",
      CFBundleTypeName: "Subtitle File",
      CFBundleTypeRole: "Viewer",
      LSTypeIsPackage: false,
      NSPersistentStoreTypeKey: "Binary",
    },
  ],
  UTExportedTypeDeclarations: [
    {
      UTTypeDescription: "VLC playlist file",
      UTTypeConformsTo: ["public.text", "public.playlist"],
      UTTypeIdentifier: "org.videolan.vlc",
      UTTypeTagSpecification: {
        "public.mime-type": [
          "application/x-videolan-vlc",
          "application/videolan-vlc",
        ],
        "public.filename-extension": ["vlc"],
      },
    },
  ],
  UTImportedTypeDeclarations: [
    {
      UTTypeConformsTo: ["public.movie"],
      UTTypeDescription: "Video files",
      UTTypeIcons: {},
      UTTypeIdentifier: "public.mpeg-4",
      UTTypeTagSpecification: {
        "public.filename-extension": ["mp4"],
      },
    },
  ],
};

const withVideoImportSupport = (config) => {
  if (!config.ios.infoPlist) config.ios.infoPlist = {};

  config.ios.infoPlist = {
    ...config.ios.infoPlist,
    ...includesEverything,
  };

  return config;
};

module.exports = withVideoImportSupport;
